/**
 * Image optimization script
 *
 * Converts large PNG/JPEG images in public/ to WebP and AVIF variants,
 * writes a manifest in public/cms/optimized-images.json, and reports savings.
 *
 * Run during build: npm run optimize-images
 */

import fs from 'fs';
import path from 'path';
import sharp from 'sharp';

const PUBLIC_DIR = path.join(process.cwd(), 'public');
const CMS_DIR = path.join(PUBLIC_DIR, 'cms');
const MANIFEST_FILE = path.join(CMS_DIR, 'optimized-images.json');
const GENERATED_DIR = path.join(process.cwd(), 'src', 'generated');
const GENERATED_FILE = path.join(GENERATED_DIR, 'optimized-images.ts');

interface OptimizationManifest {
  generatedAt: string;
  mappings: Record<string, string>;
}

const EXTENSIONS = ['.png', '.jpg', '.jpeg'];
const SKIP_DIRS = new Set(['cms', 'dist']);

function isImageFile(filePath: string): boolean {
  const ext = path.extname(filePath).toLowerCase();
  return EXTENSIONS.includes(ext);
}

function getPublicRelative(filePath: string): string {
  return '/' + path.relative(PUBLIC_DIR, filePath).replace(/\\/g, '/');
}

async function optimizeImage(filePath: string): Promise<{ webp?: string; avif?: string; savings: number }> {
  const dir = path.dirname(filePath);
  const base = path.basename(filePath, path.extname(filePath));
  const webpPath = path.join(dir, `${base}.webp`);
  const avifPath = path.join(dir, `${base}.avif`);

  const originalBuffer = fs.readFileSync(filePath);
  const originalSize = originalBuffer.length;

  let webpSaved = 0;
  let avifSaved = 0;

  // WebP at quality 85 — good balance for e-commerce product/patch images
  await sharp(originalBuffer)
    .webp({ quality: 85, effort: 4, lossless: false })
    .toFile(webpPath);

  const webpSize = fs.statSync(webpPath).size;
  webpSaved = originalSize - webpSize;

  // AVIF at quality 75 for larger files (> 200 KB) only — slower encode, smaller size
  if (originalSize > 200 * 1024) {
    await sharp(originalBuffer)
      .avif({ quality: 75, effort: 4 })
      .toFile(avifPath);
    avifSaved = originalSize - fs.statSync(avifPath).size;
  }

  return {
    webp: fs.existsSync(webpPath) ? getPublicRelative(webpPath) : undefined,
    avif: fs.existsSync(avifPath) ? getPublicRelative(avifPath) : undefined,
    savings: Math.max(webpSaved, avifSaved),
  };
}

function* walkImages(dir: string): Generator<string> {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      yield* walkImages(fullPath);
    } else if (entry.isFile() && isImageFile(fullPath)) {
      yield fullPath;
    }
  }
}

async function run() {
  console.log('🖼️  Optimizing images...\n');

  if (!fs.existsSync(CMS_DIR)) {
    fs.mkdirSync(CMS_DIR, { recursive: true });
  }

  const manifest: OptimizationManifest = {
    generatedAt: new Date().toISOString(),
    mappings: {},
  };

  let totalOriginal = 0;
  let totalSaved = 0;
  let count = 0;

  for (const imagePath of walkImages(PUBLIC_DIR)) {
    const relative = getPublicRelative(imagePath);
    const originalSize = fs.statSync(imagePath).size;
    totalOriginal += originalSize;

    try {
      const { webp, avif, savings } = await optimizeImage(imagePath);
      if (webp) {
        manifest.mappings[relative] = avif || webp;
      }
      totalSaved += savings;
      count++;
      console.log(`   ✅ ${relative} → ${manifest.mappings[relative] || relative} (saved ${(savings / 1024).toFixed(1)} KB)`);
    } catch (err) {
      console.warn(`   ⚠️  ${relative}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  fs.writeFileSync(MANIFEST_FILE, JSON.stringify(manifest, null, 2));

  // Generate a synchronous TypeScript module so the app can resolve optimized
  // image paths without a runtime fetch (no flash of unoptimized images).
  if (!fs.existsSync(GENERATED_DIR)) {
    fs.mkdirSync(GENERATED_DIR, { recursive: true });
  }
  fs.writeFileSync(
    GENERATED_FILE,
    `// Auto-generated by scripts/optimize-images.ts — do not edit manually.\n` +
      `export const optimizedImageMappings: Record<string, string> = ${JSON.stringify(
        manifest.mappings,
        null,
        2
      )};\n` +
      `export const optimizedImageGeneratedAt = '${manifest.generatedAt}';\n`
  );

  console.log('\n' + '='.repeat(50));
  console.log('📊 Image Optimization Summary');
  console.log('='.repeat(50));
  console.log(`   Images optimized: ${count}`);
  console.log(`   Original size: ${(totalOriginal / 1024 / 1024).toFixed(2)} MB`);
  console.log(`   Estimated savings: ${(totalSaved / 1024 / 1024).toFixed(2)} MB`);
  console.log(`   Manifest: ${MANIFEST_FILE}`);
  console.log(`   Generated module: ${GENERATED_FILE}`);
  console.log('='.repeat(50) + '\n');
}

run().catch((err) => {
  console.error('💥 Image optimization failed:', err);
  process.exit(1);
});
